export interface CollegeProgram {
  name: string
  state: string
  division: "D1 – Power 4" | "D1 – Group of 5" | "D1 – FCS" | "D2" | "D3" | "NAIA" | "JUCO"
}

export const COLLEGE_PROGRAMS: CollegeProgram[] = [
  // Power 4 — SEC
  { name: "University of Alabama", state: "AL", division: "D1 – Power 4" },
  { name: "University of Arkansas", state: "AR", division: "D1 – Power 4" },
  { name: "Auburn University", state: "AL", division: "D1 – Power 4" },
  { name: "University of Florida", state: "FL", division: "D1 – Power 4" },
  { name: "University of Georgia", state: "GA", division: "D1 – Power 4" },
  { name: "University of Kentucky", state: "KY", division: "D1 – Power 4" },
  { name: "Louisiana State University", state: "LA", division: "D1 – Power 4" },
  { name: "University of Mississippi", state: "MS", division: "D1 – Power 4" },
  { name: "Mississippi State University", state: "MS", division: "D1 – Power 4" },
  { name: "University of Missouri", state: "MO", division: "D1 – Power 4" },
  { name: "University of South Carolina", state: "SC", division: "D1 – Power 4" },
  { name: "University of Tennessee", state: "TN", division: "D1 – Power 4" },
  { name: "Texas A&M University", state: "TX", division: "D1 – Power 4" },
  { name: "Vanderbilt University", state: "TN", division: "D1 – Power 4" },
  { name: "University of Texas", state: "TX", division: "D1 – Power 4" },
  { name: "Oklahoma University", state: "OK", division: "D1 – Power 4" },
  // Power 4 — Big Ten
  { name: "University of Illinois", state: "IL", division: "D1 – Power 4" },
  { name: "Indiana University", state: "IN", division: "D1 – Power 4" },
  { name: "University of Iowa", state: "IA", division: "D1 – Power 4" },
  { name: "University of Maryland", state: "MD", division: "D1 – Power 4" },
  { name: "University of Michigan", state: "MI", division: "D1 – Power 4" },
  { name: "Michigan State University", state: "MI", division: "D1 – Power 4" },
  { name: "University of Minnesota", state: "MN", division: "D1 – Power 4" },
  { name: "University of Nebraska", state: "NE", division: "D1 – Power 4" },
  { name: "Northwestern University", state: "IL", division: "D1 – Power 4" },
  { name: "Ohio State University", state: "OH", division: "D1 – Power 4" },
  { name: "Penn State University", state: "PA", division: "D1 – Power 4" },
  { name: "Purdue University", state: "IN", division: "D1 – Power 4" },
  { name: "Rutgers University", state: "NJ", division: "D1 – Power 4" },
  { name: "University of Wisconsin", state: "WI", division: "D1 – Power 4" },
  { name: "UCLA", state: "CA", division: "D1 – Power 4" },
  { name: "USC", state: "CA", division: "D1 – Power 4" },
  { name: "University of Oregon", state: "OR", division: "D1 – Power 4" },
  { name: "University of Washington", state: "WA", division: "D1 – Power 4" },
  // Power 4 — Big 12
  { name: "Baylor University", state: "TX", division: "D1 – Power 4" },
  { name: "BYU", state: "UT", division: "D1 – Power 4" },
  { name: "University of Cincinnati", state: "OH", division: "D1 – Power 4" },
  { name: "University of Colorado", state: "CO", division: "D1 – Power 4" },
  { name: "University of Houston", state: "TX", division: "D1 – Power 4" },
  { name: "Iowa State University", state: "IA", division: "D1 – Power 4" },
  { name: "Kansas State University", state: "KS", division: "D1 – Power 4" },
  { name: "University of Kansas", state: "KS", division: "D1 – Power 4" },
  { name: "Oklahoma State University", state: "OK", division: "D1 – Power 4" },
  { name: "TCU", state: "TX", division: "D1 – Power 4" },
  { name: "Texas Tech University", state: "TX", division: "D1 – Power 4" },
  { name: "UCF", state: "FL", division: "D1 – Power 4" },
  { name: "West Virginia University", state: "WV", division: "D1 – Power 4" },
  { name: "Arizona State University", state: "AZ", division: "D1 – Power 4" },
  { name: "University of Arizona", state: "AZ", division: "D1 – Power 4" },
  { name: "Utah State University", state: "UT", division: "D1 – Power 4" },
  // Power 4 — ACC
  { name: "Boston College", state: "MA", division: "D1 – Power 4" },
  { name: "Clemson University", state: "SC", division: "D1 – Power 4" },
  { name: "Duke University", state: "NC", division: "D1 – Power 4" },
  { name: "Florida State University", state: "FL", division: "D1 – Power 4" },
  { name: "Georgia Tech", state: "GA", division: "D1 – Power 4" },
  { name: "University of Louisville", state: "KY", division: "D1 – Power 4" },
  { name: "University of Miami", state: "FL", division: "D1 – Power 4" },
  { name: "University of North Carolina", state: "NC", division: "D1 – Power 4" },
  { name: "NC State University", state: "NC", division: "D1 – Power 4" },
  { name: "University of Pittsburgh", state: "PA", division: "D1 – Power 4" },
  { name: "Syracuse University", state: "NY", division: "D1 – Power 4" },
  { name: "University of Virginia", state: "VA", division: "D1 – Power 4" },
  { name: "Virginia Tech", state: "VA", division: "D1 – Power 4" },
  { name: "Wake Forest University", state: "NC", division: "D1 – Power 4" },
  { name: "Notre Dame", state: "IN", division: "D1 – Power 4" },
  { name: "Stanford University", state: "CA", division: "D1 – Power 4" },
  { name: "California (Berkeley)", state: "CA", division: "D1 – Power 4" },
  // Group of 5 — Sun Belt
  { name: "Appalachian State University", state: "NC", division: "D1 – Group of 5" },
  { name: "Arkansas State University", state: "AR", division: "D1 – Group of 5" },
  { name: "Coastal Carolina University", state: "SC", division: "D1 – Group of 5" },
  { name: "Georgia Southern University", state: "GA", division: "D1 – Group of 5" },
  { name: "Georgia State University", state: "GA", division: "D1 – Group of 5" },
  { name: "James Madison University", state: "VA", division: "D1 – Group of 5" },
  { name: "Louisiana-Lafayette", state: "LA", division: "D1 – Group of 5" },
  { name: "Louisiana-Monroe", state: "LA", division: "D1 – Group of 5" },
  { name: "Marshall University", state: "WV", division: "D1 – Group of 5" },
  { name: "Old Dominion University", state: "VA", division: "D1 – Group of 5" },
  { name: "South Alabama", state: "AL", division: "D1 – Group of 5" },
  { name: "Southern Miss", state: "MS", division: "D1 – Group of 5" },
  { name: "Texas State University", state: "TX", division: "D1 – Group of 5" },
  { name: "Troy University", state: "AL", division: "D1 – Group of 5" },
  // Group of 5 — American Athletic
  { name: "Charlotte", state: "NC", division: "D1 – Group of 5" },
  { name: "East Carolina University", state: "NC", division: "D1 – Group of 5" },
  { name: "Florida Atlantic University", state: "FL", division: "D1 – Group of 5" },
  { name: "Memphis University", state: "TN", division: "D1 – Group of 5" },
  { name: "Navy", state: "MD", division: "D1 – Group of 5" },
  { name: "North Texas", state: "TX", division: "D1 – Group of 5" },
  { name: "Rice University", state: "TX", division: "D1 – Group of 5" },
  { name: "SMU", state: "TX", division: "D1 – Power 4" },
  { name: "South Florida", state: "FL", division: "D1 – Group of 5" },
  { name: "Temple University", state: "PA", division: "D1 – Group of 5" },
  { name: "Tulane University", state: "LA", division: "D1 – Group of 5" },
  { name: "Tulsa University", state: "OK", division: "D1 – Group of 5" },
  { name: "UTSA", state: "TX", division: "D1 – Group of 5" },
  { name: "UTEP", state: "TX", division: "D1 – Group of 5" },
  { name: "Wichita State", state: "KS", division: "D1 – Group of 5" },
  // Group of 5 — Mountain West
  { name: "Air Force Academy", state: "CO", division: "D1 – Group of 5" },
  { name: "Boise State University", state: "ID", division: "D1 – Group of 5" },
  { name: "Colorado State University", state: "CO", division: "D1 – Group of 5" },
  { name: "Fresno State", state: "CA", division: "D1 – Group of 5" },
  { name: "Hawaii", state: "HI", division: "D1 – Group of 5" },
  { name: "Nevada", state: "NV", division: "D1 – Group of 5" },
  { name: "New Mexico", state: "NM", division: "D1 – Group of 5" },
  { name: "San Diego State", state: "CA", division: "D1 – Group of 5" },
  { name: "San Jose State", state: "CA", division: "D1 – Group of 5" },
  { name: "UNLV", state: "NV", division: "D1 – Group of 5" },
  { name: "Utah State", state: "UT", division: "D1 – Group of 5" },
  { name: "Wyoming", state: "WY", division: "D1 – Group of 5" },
  // Group of 5 — MAC & CUSA
  { name: "Akron", state: "OH", division: "D1 – Group of 5" },
  { name: "Ball State", state: "IN", division: "D1 – Group of 5" },
  { name: "Bowling Green", state: "OH", division: "D1 – Group of 5" },
  { name: "Buffalo", state: "NY", division: "D1 – Group of 5" },
  { name: "Central Michigan University", state: "MI", division: "D1 – Group of 5" },
  { name: "Eastern Michigan University", state: "MI", division: "D1 – Group of 5" },
  { name: "Kent State", state: "OH", division: "D1 – Group of 5" },
  { name: "Miami (Ohio)", state: "OH", division: "D1 – Group of 5" },
  { name: "Northern Illinois University", state: "IL", division: "D1 – Group of 5" },
  { name: "Ohio University", state: "OH", division: "D1 – Group of 5" },
  { name: "Toledo", state: "OH", division: "D1 – Group of 5" },
  { name: "Western Michigan University", state: "MI", division: "D1 – Group of 5" },
  { name: "Jacksonville State", state: "AL", division: "D1 – Group of 5" },
  { name: "Liberty University", state: "VA", division: "D1 – Group of 5" },
  { name: "Louisiana Tech", state: "LA", division: "D1 – Group of 5" },
  { name: "Middle Tennessee State", state: "TN", division: "D1 – Group of 5" },
  { name: "New Mexico State", state: "NM", division: "D1 – Group of 5" },
  { name: "Sam Houston State", state: "TX", division: "D1 – Group of 5" },
  { name: "Western Kentucky University", state: "KY", division: "D1 – Group of 5" },
  // FCS — Major programs
  { name: "Abilene Christian University", state: "TX", division: "D1 – FCS" },
  { name: "Albany", state: "NY", division: "D1 – FCS" },
  { name: "Alcorn State", state: "MS", division: "D1 – FCS" },
  { name: "Austin Peay", state: "TN", division: "D1 – FCS" },
  { name: "Bethune-Cookman", state: "FL", division: "D1 – FCS" },
  { name: "Cal Poly", state: "CA", division: "D1 – FCS" },
  { name: "Central Arkansas", state: "AR", division: "D1 – FCS" },
  { name: "Chattanooga", state: "TN", division: "D1 – FCS" },
  { name: "Colgate", state: "NY", division: "D1 – FCS" },
  { name: "Dartmouth", state: "NH", division: "D1 – FCS" },
  { name: "Davidson", state: "NC", division: "D1 – FCS" },
  { name: "Dayton", state: "OH", division: "D1 – FCS" },
  { name: "Delaware", state: "DE", division: "D1 – FCS" },
  { name: "Drake", state: "IA", division: "D1 – FCS" },
  { name: "Duquesne", state: "PA", division: "D1 – FCS" },
  { name: "Eastern Illinois", state: "IL", division: "D1 – FCS" },
  { name: "Eastern Kentucky", state: "KY", division: "D1 – FCS" },
  { name: "Eastern Washington", state: "WA", division: "D1 – FCS" },
  { name: "Elon", state: "NC", division: "D1 – FCS" },
  { name: "Florida A&M", state: "FL", division: "D1 – FCS" },
  { name: "Fordham", state: "NY", division: "D1 – FCS" },
  { name: "Furman", state: "SC", division: "D1 – FCS" },
  { name: "Gardner-Webb", state: "NC", division: "D1 – FCS" },
  { name: "Georgetown", state: "DC", division: "D1 – FCS" },
  { name: "Grambling State", state: "LA", division: "D1 – FCS" },
  { name: "Harvard", state: "MA", division: "D1 – FCS" },
  { name: "Holy Cross", state: "MA", division: "D1 – FCS" },
  { name: "Howard University", state: "DC", division: "D1 – FCS" },
  { name: "Idaho", state: "ID", division: "D1 – FCS" },
  { name: "Illinois State", state: "IL", division: "D1 – FCS" },
  { name: "Incarnate Word", state: "TX", division: "D1 – FCS" },
  { name: "Indiana State", state: "IN", division: "D1 – FCS" },
  { name: "Jackson State", state: "MS", division: "D1 – FCS" },
  { name: "Kennesaw State", state: "GA", division: "D1 – FCS" },
  { name: "Lamar University", state: "TX", division: "D1 – FCS" },
  { name: "Lehigh", state: "PA", division: "D1 – FCS" },
  { name: "Maine", state: "ME", division: "D1 – FCS" },
  { name: "McNeese State", state: "LA", division: "D1 – FCS" },
  { name: "Mississippi Valley State", state: "MS", division: "D1 – FCS" },
  { name: "Missouri State", state: "MO", division: "D1 – FCS" },
  { name: "Montana", state: "MT", division: "D1 – FCS" },
  { name: "Montana State", state: "MT", division: "D1 – FCS" },
  { name: "Morgan State", state: "MD", division: "D1 – FCS" },
  { name: "Murray State", state: "KY", division: "D1 – FCS" },
  { name: "Nicholls State", state: "LA", division: "D1 – FCS" },
  { name: "Norfolk State", state: "VA", division: "D1 – FCS" },
  { name: "North Carolina A&T", state: "NC", division: "D1 – FCS" },
  { name: "North Carolina Central", state: "NC", division: "D1 – FCS" },
  { name: "North Dakota", state: "ND", division: "D1 – FCS" },
  { name: "North Dakota State", state: "ND", division: "D1 – FCS" },
  { name: "Northeastern", state: "MA", division: "D1 – FCS" },
  { name: "Northern Arizona", state: "AZ", division: "D1 – FCS" },
  { name: "Northern Iowa", state: "IA", division: "D1 – FCS" },
  { name: "Northwestern State", state: "LA", division: "D1 – FCS" },
  { name: "Penn", state: "PA", division: "D1 – FCS" },
  { name: "Portland State", state: "OR", division: "D1 – FCS" },
  { name: "Prairie View A&M", state: "TX", division: "D1 – FCS" },
  { name: "Princeton", state: "NJ", division: "D1 – FCS" },
  { name: "Rhode Island", state: "RI", division: "D1 – FCS" },
  { name: "Richmond", state: "VA", division: "D1 – FCS" },
  { name: "Sacramento State", state: "CA", division: "D1 – FCS" },
  { name: "Saint Francis", state: "PA", division: "D1 – FCS" },
  { name: "Sam Houston", state: "TX", division: "D1 – FCS" },
  { name: "Samford", state: "AL", division: "D1 – FCS" },
  { name: "South Carolina State", state: "SC", division: "D1 – FCS" },
  { name: "South Dakota", state: "SD", division: "D1 – FCS" },
  { name: "South Dakota State", state: "SD", division: "D1 – FCS" },
  { name: "Southeast Missouri State", state: "MO", division: "D1 – FCS" },
  { name: "Southeastern Louisiana", state: "LA", division: "D1 – FCS" },
  { name: "Southern Illinois", state: "IL", division: "D1 – FCS" },
  { name: "Southern University", state: "LA", division: "D1 – FCS" },
  { name: "Stephen F. Austin", state: "TX", division: "D1 – FCS" },
  { name: "Stony Brook", state: "NY", division: "D1 – FCS" },
  { name: "Tarleton State", state: "TX", division: "D1 – FCS" },
  { name: "Tennessee State", state: "TN", division: "D1 – FCS" },
  { name: "Tennessee Tech", state: "TN", division: "D1 – FCS" },
  { name: "Texas Southern", state: "TX", division: "D1 – FCS" },
  { name: "Towson", state: "MD", division: "D1 – FCS" },
  { name: "UC Davis", state: "CA", division: "D1 – FCS" },
  { name: "Utah Tech", state: "UT", division: "D1 – FCS" },
  { name: "Villanova", state: "PA", division: "D1 – FCS" },
  { name: "VMI", state: "VA", division: "D1 – FCS" },
  { name: "Wagner", state: "NY", division: "D1 – FCS" },
  { name: "Weber State", state: "UT", division: "D1 – FCS" },
  { name: "Western Carolina", state: "NC", division: "D1 – FCS" },
  { name: "Western Illinois", state: "IL", division: "D1 – FCS" },
  { name: "William & Mary", state: "VA", division: "D1 – FCS" },
  { name: "Wofford", state: "SC", division: "D1 – FCS" },
  { name: "Yale", state: "CT", division: "D1 – FCS" },
  // D2 — Key programs (especially Texas region)
  { name: "Angelo State University", state: "TX", division: "D2" },
  { name: "Midwestern State University", state: "TX", division: "D2" },
  { name: "Tarleton State University", state: "TX", division: "D2" },
  { name: "Texas A&M-Commerce", state: "TX", division: "D2" },
  { name: "Texas A&M-Kingsville", state: "TX", division: "D2" },
  { name: "West Texas A&M", state: "TX", division: "D2" },
  { name: "Harding University", state: "AR", division: "D2" },
  { name: "Henderson State", state: "AR", division: "D2" },
  { name: "Ouachita Baptist", state: "AR", division: "D2" },
  { name: "Arkansas Tech", state: "AR", division: "D2" },
  { name: "Henderson State University", state: "AR", division: "D2" },
  { name: "Southwestern Oklahoma State", state: "OK", division: "D2" },
  { name: "Northwestern Oklahoma State", state: "OK", division: "D2" },
  { name: "Southeastern Oklahoma State", state: "OK", division: "D2" },
  { name: "Fort Hays State", state: "KS", division: "D2" },
  { name: "Pittsburg State", state: "KS", division: "D2" },
  { name: "Washburn University", state: "KS", division: "D2" },
  { name: "Missouri Southern", state: "MO", division: "D2" },
  { name: "Missouri Western", state: "MO", division: "D2" },
  { name: "Central Missouri", state: "MO", division: "D2" },
  { name: "Northwest Missouri State", state: "MO", division: "D2" },
  { name: "Emporia State", state: "KS", division: "D2" },
  { name: "Colorado School of Mines", state: "CO", division: "D2" },
  { name: "Colorado Mesa", state: "CO", division: "D2" },
  { name: "CSU Pueblo", state: "CO", division: "D2" },
  { name: "West Georgia", state: "GA", division: "D2" },
  { name: "Valdosta State", state: "GA", division: "D2" },
  { name: "Delta State", state: "MS", division: "D2" },
  { name: "Tuskegee University", state: "AL", division: "D2" },
  // D3 — Key programs
  { name: "Hardin-Simmons University", state: "TX", division: "D3" },
  { name: "Howard Payne University", state: "TX", division: "D3" },
  { name: "McMurry University", state: "TX", division: "D3" },
  { name: "Southwestern University", state: "TX", division: "D3" },
  { name: "Trinity University", state: "TX", division: "D3" },
  { name: "University of Mary Hardin-Baylor", state: "TX", division: "D3" },
  { name: "Belhaven University", state: "MS", division: "D3" },
  { name: "Austin College", state: "TX", division: "D3" },
  // NAIA — Key Texas/regional programs
  { name: "Bacone College", state: "OK", division: "NAIA" },
  { name: "Langston University", state: "OK", division: "NAIA" },
  { name: "Oklahoma Panhandle State", state: "OK", division: "NAIA" },
  { name: "Southeastern University", state: "FL", division: "NAIA" },
  { name: "Wayland Baptist University", state: "TX", division: "NAIA" },
  { name: "Texas College", state: "TX", division: "NAIA" },
  { name: "Panola College", state: "TX", division: "JUCO" },
  { name: "Blinn College", state: "TX", division: "JUCO" },
  { name: "Navarro College", state: "TX", division: "JUCO" },
  { name: "Tyler Junior College", state: "TX", division: "JUCO" },
  { name: "Kilgore College", state: "TX", division: "JUCO" },
  { name: "Northeast Texas Community College", state: "TX", division: "JUCO" },
  { name: "Trinity Valley Community College", state: "TX", division: "JUCO" },
  { name: "Cisco College", state: "TX", division: "JUCO" },
  { name: "Hill College", state: "TX", division: "JUCO" },
  { name: "Lon Morris College", state: "TX", division: "JUCO" },
  { name: "Southwest Mississippi Community College", state: "MS", division: "JUCO" },
  { name: "Copiah-Lincoln Community College", state: "MS", division: "JUCO" },
  { name: "Itawamba Community College", state: "MS", division: "JUCO" },
  { name: "Jones College", state: "MS", division: "JUCO" },
  { name: "Snow College", state: "UT", division: "JUCO" },
  { name: "Coffeyville Community College", state: "KS", division: "JUCO" },
  { name: "Garden City Community College", state: "KS", division: "JUCO" },
  { name: "Butler Community College", state: "KS", division: "JUCO" },
  { name: "Iowa Western Community College", state: "IA", division: "JUCO" },
  { name: "Hutchinson Community College", state: "KS", division: "JUCO" },
]

export function searchPrograms(query: string, limit = 8): CollegeProgram[] {
  if (!query || query.length < 2) return []
  const q = query.toLowerCase()
  return COLLEGE_PROGRAMS.filter(p => p.name.toLowerCase().includes(q)).slice(0, limit)
}
